version: "2"

services:
  flexget:
    build: .
    volumes:
      - ./config:/config
      - ./data:/data
      - ./storage:/storage
    ports:
      - 5050:5050
    environment:
      - FG_WEBUI_PASSWD=ultrasecretpassword
      - TORRENT_PLUGIN=transmission
      - TZ=America/Argentina/Mendoza

  transmission:
    image : mool/transmission
    volumes:
      - ./storage:/media
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Argentina/Mendoza
      - TRANSMISSION_DOWNLOAD_DIR=/media/downloads/complete
      - TRANSMISSION_INCOMPLETE_DIR=/media/downloads/incomplete
      - TRANSMISSION_RPC_USERNAME=transmission
      - TRANSMISSION_RPC_PASSWORD=moolandia31284
      - TRANSMISSION_RPC_AUTHENTICATION_REQUIRED=true
      - TRANSMISSION_WEB_HOME=/combustion-release/
      - TARGET_PATH=/media
